PREFIX oml: <http://opencaesar.io/oml#>
PREFIX component: <https://www.modelware.io/sierra/component#>

SELECT ?port ?comp ?dir ?isConnected
WHERE {
  ?port a component:Port .
  OPTIONAL { ?port (component:portOf|^component:hasPort) ?comp }
  OPTIONAL { ?port component:direction ?dir }
  BIND(EXISTS {
    ?conn a component:Connection .
    { ?conn oml:hasSource ?port } UNION { ?conn oml:hasTarget ?port }
  } AS ?isConnected)
}
